#!/bin/sh
# set -eou pipefail
clear
normal="\e[0m"
bold="\e[1m"
green="\e[32m"
orange="\e[33m"
if ! command -v /bin/fzf &>/dev/null; then
	printf "REQUIRES PROGRAM FZF!" && exit 2
fi
if [ ! -d "${TEMPDIR}" ] || [ -z "${TEMPDIR}" ]; then
	mktemp -d --suffix="-$(date '+%m-%d-%Y')" &>/dev/null
	TEMPDIR="$(/bin/ls -ltdr ${TEMP}/tmp.* 2>/dev/null | head -1 | awk '{print $NF}' 2>/dev/null)"
else
	exit 1
fi
CLIPFILE="${TEMPDIR}/tmpclp-$(date '+%m-%d-%Y').txt"

# if clipfile exists, create view of clipfile and put selected text from clipfile to clipboard
if [ -f "${CLIPFILE}" ]; then
    CLPMAN="$(/bin/cat -p "$CLIPFILE" | uniq | /bin/fzf -m --prompt="Copy : " --border --margin=5% --color=dark --height=100% --reverse --header-first --header=" CLIPXF ")"
#     CLPMAN="$("$HOME"/.cargo/bin/bat -p "$CLIPFILE" | uniq | /bin/fzf -m --prompt="Copy : " --border --margin=5% --color=dark --height=100% --reverse --header-first --header=" CLIPXF ")"
    if [ "${CLPMAN}" ]; then
        printf "%s\n" "$CLPMAN" | /bin/xclip -sel c || exit 1
    else
        exit 1
    fi

# if clipfile doesn't exist, create it, copy clipboard into clipfile, then create view of clipfile and, if desired, copy some text from clipfile back to clipboard
else
#	/bin/touch "$clipfile" \
#		&& /bin/chmod 600 "$clipfile" \
#		&& /bin/echo -e "$CLPMAN" | /bin/xclip -sel c \
#		&& printf "${green}No ${bold}${orange}Clipman${normal}${green}, empty ${bold}%s${normal}${green} created!\n" "$clipfile"
    /bin/touch "$CLIPFILE" \
		&& /bin/chmod 600 "$CLIPFILE" \
		&& printf "%s\n" "$(/bin/xclip -sel c -o)" >> "$CLIPFILE" \
		&& printf "${green}No ${bold}${orange}Clipman${normal}${green}, empty ${bold}%s${normal}${green} created!\n" "$CLIPFILE"

    CLPMAN="$("$HOME"/.cargo/bin/bat "$CLIPFILE" | uniq | /bin/fzf --prompt="Copy : " --border --margin=5% --color=dark --height=100% --reverse --header-first --header=" CLIPXF ")"
    if [[ "$CLPMAN" ]]; then
  		/bin/echo -e "$CLPMAN" 
        printf "%s\n" "$CLPMAN" | /bin/xclip -sel c
    else
        exit 1
    fi
fi
exit 0

