#!/bin/bash
# Simple encrypt program

# comment if not using 'exa'

my_selection="$(exa -a | fzf --height 95% --reverse --info hidden --prompt "ENCRYPT FILE: "  --header-first --preview ' cd_pre="$(echo $(pwd)/$(echo {}))";
                    echo $cd_pre;
                    echo;
                    exa -a --color=always "${cd_pre}";
                    bat --style=numbers --theme=ansi --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:65%)"

# uncomment if not using 'exa'

# my_selection="$(/bin/ls -a | fzf --height 95% --reverse --info hidden --prompt "ENCRYPT FILE: "  --header-first --preview ' cd_pre="$(echo $(pwd)/$(echo {}))";
#                     echo $cd_pre;
#                     echo;
#                     /bin/ls -a --color=always "${cd_pre}";
#                     /bin/cat --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:65%)"

if [[ "${my_selection}" ]]
then
    printf "Recipient: \n"
    read -r recipient
    printf "Output File: \n"
    read -r output_file
    if [[ "${my_recipient}" && "${output_file}" ]]
    then
        printf "Encrypting %s for %s.\n" "${my_selection}", "${my_recipient}"
        gpg --armor --output "${output_file}".enc --encrypt --recipient "${my_recipient}" "${my_selection}"
        read -p "Would you like to Delete Original File?:(Y/n) " -n 1 -r
        if [[ "$REPLY" =~ ^[Yy]$ ]]; then
                rm -i "${my_selection}"
            elif [[ "$REPLY" =~ ^[Nn]$ ]]; then
                printf "\nNot Deleting Original File\n"
            fi
    else
        printf "Error either in my_selection, Recipient, Output File!\n"
        exit 1
    fi
else
    printf "No my_selection input!\n"
    exit 2
fi
sleep 1
exit 0
