#!/bin/bash
# hacked together way of switching between github gitlab
# stop script if any step fails
set -eou pipefail
ACTION="$1"
REPO="$2"

pushd "$REPO"
if [ -z "$REPO" ]; then
    /usr/bin/figlet "ERROR!!"
    printf "ERROR: Please include repo name followed by filename or \* \(glob\) for entire dir.\n"
  exit 1
fi

if [[ "$ACTION" == "push" ]]; then
    /usr/bin/git status || exit 1
    read -p "Would you like to push changes?: " -n 1 -r
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
            /usr/bin/git add . || exit 1
        elif [[ "$REPLY" =~ ^[Nn]$ ]]; then
            printf "\n%s" "No Changes Pushed" || exit 1
            sleep 0.5
            exit
        fi

    printf "\n%s" "Create Comment: "
    read -r MESSAGE

        /usr/bin/git commit -m "$MESSAGE" || exit 1
        /usr/bin/git push || exit 1
        
    /usr/bin/figlet "PUSH COMPLETE!!"
    popd || exit 1
    sleep 0.5
    exit 0
elif [[ "$ACTION" == "pull" ]]; then
    /usr/bin/git pull --rebase
    /usr/bin/figlet "PULL COMPLETE!!"
    popd || exit 1
    sleep 0.5
    exit 0
elif [[ "$ACTION" == "check" ]]; then
    /usr/bin/git remote update && git status -uno
    exit 0
else
    /usr/bin/figlet "ERROR!!"
    printf "ERROR! Usage:  gitxf [push or pull or check] [repo_name]\n"
    popd || exit 1
    sleep 0.5
    exit 1
fi

