#!/bin/bash
# USE -- ctrl+j and ctrl+k down/up respectively for file names
# USE shift+tab to select multiple items
# (not implemented properly yet) # if preview of file is there use -- alt+j and alt+k down/up respectively for the preview of file contents
set -o pipefail
my_reqs=("fzf")
for each_single in "${my_reqs[@]}"; do
	if ! command -v "${each_single}" &>/dev/null; then
		printf "\n\t%s not found\n" "${each_single}"
	# do you want to install?
		read -p "Would you like to install?: " -n 1 -r
		if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
			if [[ -d "/etc/apt" ]]; then
				sudo apt install "$each_single" || exit 1
			elif [[ -d "/etc/pacman.d" ]]; then
				sudp pacman -S "${each_single}" || exit 1
			else
				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "${each_single}" && exit 1
			fi
		else
			printf "exiting program" && exit 0
		fi
	fi
done
if [[ "${1}" = "\*" ]]; then
	git add .
	read -p "Add commit my_mesg: " -r my_mesg
	[[ "${my_mesg}" ]] || exit 1
	git commit -m "${my_mesg}"
	git push
	exit 0
else
	/usr/bin/git status -uall -s | sort -u || exit 1
	untracked_files="$(/usr/bin/git status -uall -s | sort -u | /usr/bin/fzf -m --prompt="Add Files : " --border --margin=5% --color=dark --height=100% --reverse --header-first --header=" GPUSH ")" 

	if [[ "${untracked_files}" ]]; then
		for my_file in $(printf '%s' "${untracked_files}" | awk '{print $NF}'); do
			git add "${my_file}"
		done

		read -p "Would you like to Commit?(Y/n): " -n 1 -r
		if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
			printf "\n"
			read -p "Add commit my_mesg: " -r my_mesg
			[[ -n "${my_mesg}" ]] || exit 1
			git commit -m "${my_mesg}"
			printf "\n"
			read -p "Would you like to Push?(Y/n): " -n 1 -r
			if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
				git push || exit 1
				printf "\nExiting Program\n" && exit 0
			else
				printf "\nExiting Program\n" && exit 0
			fi
		else
			printf "\nNeed to enter Y/n\n"
			printf "\nExiting Program\n" && exit 0
		fi
		exit 0
	else
		exit 1
	fi
fi
