#!/bin/bash
# set -eou pipefail
clear
cd "${HOME}"/.config/vimwiki || exit 1
my_files="$(/usr/bin/grep -HRniEI "${*}" "${PWD}" | /usr/bin/awk -F ':' '{print $1}' | /usr/bin/sort -u)"
if [ -z "${my_files}" ]; then 
	printf "no match found\n" && exit 1
fi 

# comment if not using 'exa' or 'bat'

my_selection="$( printf '%s' "${my_files}" | /usr/bin/fzf -m --header-first --header='gWiki' --height 100% --reverse --info hidden --prompt 'PREVIEW:' --preview ' my_file_pre="$(echo $(echo {}))";
		echo;
		exa -a --color=always "${my_file_pre}";
		bat --style=numbers --theme=ansi --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:70%)"

# uncomment if not using 'exa' or 'bat'

# my_selection="$( printf '%s' "${my_files}" | /usr/bin/fzf -m --header-first --header='gWiki' --height 100% --reverse --info hidden --prompt 'PREVIEW:' --preview ' my_file_pre="$(echo $(echo {}))";
# 		echo;
# 		/bin/ls -a --color=always "${my_file_pre}";
# 		/bin/cat --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:70%)"

if [ -f "${my_selection}" ]; then
	for my_file in "${my_selection}"; do
		if [ "${my_file}" == *.txt ] || [ "${my_file}" == *.sh ] || [ "${my_file}" == *.md ] || [ "${my_file}" == *.lua ] || [ "${my_file}" == *.conf ] || [ "${my_file}" == .*rc ] || [ "${my_file}" == *rc ] || [ "${my_file}" == autostart ] || [ "${my_file}" == *.log ] || [ "${my_file}" == *.go ] || [ "${my_file}" == *.mod ]; then
			nvim "${my_selection}" || exit 1
		elif [ "${my_file}" == *.docx ] || [ "${my_file}" == *.odt ]; then
			/usr/bin/libreoffice "${my_selection}" || exit 1
		elif [ "${my_file}" == *.jpg ] || [ "${my_file}" == *.png ]; then
			/usr/bin/sxiv "${my_selection}" || exit 1
		elif [ "${my_file}" == *.xcf ]; then
			/usr/bin/gimp "${my_selection}" || exit 1
		else
			nvim "${my_selection}" || exit 1
		fi
	done
fi
cd "${OLDPWD}" || exit 1
exit 0
