#!/bin/bash
# check if fzf and apropos are installed, install if not
set -eou pipefail
my_reqs=("fzf" "apropos")

for each_single in "${my_reqs[@]}"; do
	if ! command -v "${each_single}" &>/dev/null; then
		printf "\n\t%s not found\n" "${each_single}"
# 	    do you want to install?
		read -p "Would you like to install?: " -n 1 -r
		if [ "$REPLY" =~ ^[Yy]$ ]; then
# 			if command -v apt &>/dev/null; then
			if [ -d "/etc/apt" ]; then
				sudo apt install "${each_single}" || exit 1
# 			elif command -v packman &>/dev/null; then
			elif [ -d "/etc/pacman.d" ]; then
				sudp pacman -S "${each_single}" || exit 1
			else
				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "${each_single}" && exit 1
			fi
		else
			printf "exiting program" && exit 0
		fi
	fi
done

# get command or keyword/phrase
read -r -p "manpages: " my_query
[ "${my_query}" ] || exit 1

# check if command is a builtin
if [ "$(type -ta "${my_query}" | head -1)" == "builtin" ] && [ "${my_query}" != "test" ]; then
	tmux neww bash -c "man $(echo "${SHELL}" | awk -F'/' '{print $NF}') | \less '+/${my_query}\ \['" || exit 1

# check if there is manpage
elif [ "$(apropos "${my_query}" &>/dev/null;printf '%s' "$?")" == "0" ] ; then
	if [ "${my_query}" == "test" ]; then
		tmux neww bash -c "man ${my_query}" || exit 1
		exit 0
	else
		my_selected="$(apropos "${my_query}" | sort -u | fzf --border --margin=5% --color=dark --height=100% --reverse)"
		[ "${my_selected}" ] || exit 1
# 		select and open manpage
		if [ -n "${my_selected}" ]; then
			tmux neww bash -c "man $(echo -e  "${my_selected}" | tr -d ' ' | awk -F'(' '{print $1"."$2}' | cut -d ')' -f 1)" || exit 1
			exit 0
		fi
	fi

# check if there is not a manpage
elif [ "$(apropos "${my_query}" &>/dev/null;printf '%s' "$?")" == "16" ]; then
	exit 16
# 	printf "%s" "Unable to find man with keyword/phrase or builtin command to lookup." && exit 16

else
# 	printf "%s" "Unable to complete request for some reason" && exit 1
	exit 1
fi
exit 0

