#!/bin/bash
# check if fzf and apropos are installed, install if not
set -eou pipefail
REQUIREMENTS=("fzf" "apropos")

for SINGLE in "${REQUIREMENTS[@]}"; do
	if ! command -v "$SINGLE" &>/dev/null; then
		printf "\n\t%s not found\n" "$SINGLE"
# 	    do you want to install?
		read -p "Would you like to install?: " -n 1 -r
		if [ "$REPLY" =~ ^[Yy]$ ]; then
			if [ -d "/etc/apt" ]; then
				sudo apt install "$SINGLE" -y || exit 1
			elif [ -d "/etc/pacman.d" ]; then
				sudp pacman -S "$SINGLE" || exit 1
			else
				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "$SINGLE" && exit 1
			fi
		else
			printf "exiting program" && exit 0
		fi
	fi
done

# server
# get command or keyword/phrase
read -r -p "query: " QUERY
[ "$QUERY" ] || exit 1

# check if command is a builtin
if [ $(type -ta "$QUERY" | head -1) == "builtin" ]; then
	man "$(echo "$SHELL" | awk -F'/' '{print $NF}')" 2>&1 | \less "+/$QUERY\ \[" || exit 1

# check if there is not a manpage
elif [ $(apropos "$QUERY" &>/dev/null;echo "$?") == "16" ]; then
	printf "%s\n" "Unable to find man with keyword/phrase or builtin command to lookup." && exit 16

# check if there is manpage
elif [ $(apropos "$QUERY" &>/dev/null;echo "$?") == "0" ]; then
	SELECTED=$(apropos "$QUERY" | sort -u | fzf --border --margin=5% --color=dark --height=100% --reverse)
# select and open manpage
	if [ "$SELECTED" ]; then
		man "$(echo -e  "$SELECTED" | tr -d ' ' | awk -F'(' '{print $1"."$2}' | cut -d ')' -f 1)" || exit 1
	fi
else
	printf "%s\n" "Unable to complete request for some reason" && exit 1
fi
exit 0
