#!/bin/bash
# --------------------------- Simple encrypt program -------------------------- #

# --------------------- comment out if you don't use 'eza' -------------------- #

my_selection="$(eza -a | fzf --height 95% --reverse --info hidden --prompt "encrypt file: "  --header-first --preview ' cd_pre="$(echo $(pwd)/$(echo {}))";
                    echo $cd_pre;
                    echo;
                    eza -a --color=always "${cd_pre}";
                    termpix --width 100 --true-color {} 2>/dev/null;
                    bat --style=numbers --theme=ansi --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:65%)"
# --------------------------------------  ------------------------------------- #

# ---------------------- uncomment if you don't use 'eza' --------------------- #

# my_selection="$(/bin/ls -a | /bin/fzf --height 95% --reverse --info hidden --prompt "ENCRYPT FILE: "  --header-first --preview ' cd_pre="$(echo $(pwd)/$(echo {}))";
#                     echo $cd_pre;
#                     echo;
#                     eza -a --color=always "${cd_pre}";
#                     termpix --width 100 --true-color {} 2>/dev/null;
#                     bat --style=numbers --theme=ansi --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:65%)"
# --------------------------------------  ------------------------------------- #

if [[ "${my_selection}" ]]; then
    printf "Signing %s.\n" "${my_selection}"
    /bin/gpg --sign "${my_selection}"
else
    printf "No my_selection Input!\n"
    exit 2
fi
sleep 1
exit 0
