#!/bin/bash
clear
# pushd "$HOME"/.config/vimwiki/docs || exit 1
cd "$HOME"/.config/vimwiki/docs || exit 1
while true; do
	find_files="$(/usr/bin/grep -HRniEI "$*" ./computer/windows | /usr/bin/awk -F ':' '{print $1}' | /usr/bin/sort -u)"
	if [ -z "$find_files" ]; then 
		printf "no match found" && exit 1
	fi 
	selection="$(printf '%s' "$find_files" | /usr/bin/fzf -m --header-first --header='winWiki' --height 100% --reverse --info hidden --prompt 'PREVIEW:' --preview ' file_pre="$(echo $(echo {}))";
            echo;
            exa -a --color=always "${file_pre}";
            bat --style=numbers --theme=ansi --color=always {} 2>/dev/null' --bind alt-j:preview-down,alt-k:preview-up --preview-window=right:70%)"
    if [ -f "$selection" ]; then
        for file in "$selection"; do
            if [ "$file" == *.txt ] || [ "$file" == *.sh ] || [ "$file" == *.md ] || [ "$file" == *.lua ] || [ "$file" == *.conf ] || [ "$file" == .*rc ] || [ "$file" == *rc ] || [ "$file" == autostart ] || [ "$file" == *.log ] || [ "$file" == *.go ] || [ "$file" == *.mod ]; then
                /usr/bin/nvim "$selection" || exit 1
            elif [ "$file" == *.docx ] || [ "$file" == *.odt ]; then
                /usr/bin/libreoffice "$selection" || exit 1
            elif [ "$file" == *.jpg ] || [ "$file" == *.png ]; then
                /usr/bin/sxiv "$selection" || exit 1
            elif [ "$file" == *.xcf ]; then
                /usr/bin/gimp "$selection" || exit 1
            else
                /usr/bin/nvim "$selection" || exit 1
            fi
        done
    fi
done
# popd || exit 1
cd "$OLDPWD" || exit 1
exit 0

