#!/bin/bash
#/bin/zsh
#/usr/bin/ksh93
REQUIREMENTS=("fzf")
for SINGLE in "${REQUIREMENTS[@]}"; do
	if ! command -v "$SINGLE" &>/dev/null; then
		printf "\n\t%s not found\n" "$SINGLE"
	# do you want to install?
		read -p "Would you like to install?: " -n 1 -r
		if [[ "$REPLY" =~ ^[Yy]$ ]]; then
			if [[ -d "/etc/apt" ]]; then
				sudo apt install "$SINGLE" || exit 1
			elif [[ -d "/etc/pacman.d" ]]; then
				sudp pacman -S "$SINGLE" || exit 1
			else
				printf "\n\t\tpackage not found\n\tuse your pkg manager to install %s\n" "$SINGLE" && exit 1
			fi
		else
			printf "exiting program" && exit 0
		fi
	fi
done

#for file in ${HOME}/functions/gitxf/*; do
	#source $file
#done
#export -f "${HOME}"/functions/gitxf_funcs/xf_action
if [ -f "${HOME}"/functions/gitxf_funcs/xf_action ]; then
	source "${HOME}"/functions/gitxf_funcs/xf_action || exit 1
else
	printf "xf_action not found" && exit 1
fi

#export FPATH=${HOME}/functions/gitxf

xf_action "${@}"

exit "${?}"


